MCSTOGO/Models/ErrorViewModel.cs
using System;

namespace MCSTOGO.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MCSTOGO/Models/PhotModel.cs
namespace MCSTOGO.Models
{
    public class PhotoModel
    {
        public string Id { get; set; }
        public string Url { get; set; }
        public string base64img { get; set; }
    }
}

MCSTOGO/Models/PostModel.cs
using System.Buffers.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace MCSTOGO.Models
{
    public class PostInputModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Entrer le nom du post")]
        [Display(Name = "Nom")]
        public string NomPost { get; set; }

        [Required(ErrorMessage = "Renseigner le prix svp")]
        [Display(Name = "Prix")]
        public string Prix { get; set; }

        [Display(Name = "Quartier/Ville/Emplacement")]
        [Required(ErrorMessage = "Svp entrez le lieu")]
        public string Lieu { get; set; }  
        [Display(Name = "Type de contrat")]
        [Required(ErrorMessage = "Svp entrez le type de contrat")]
        public string TypeContrat { get; set; }

        public string Description { get; set; }
        [Display(Name = "Date d'ajout")] public string DateAjout { get; set; }
        [Display(Name = "Photo principale")] public IFormFile Photo1 { get; set; }
        [Display(Name = "Photo Secondaire")] public IFormFile Photo2 { get; set; }
        [Display(Name = "Photo Optionnel")] public IFormFile Photo3 { get; set; }
        [Display(Name = "Photo optionnel")] public IFormFile Photo4 { get; set; }
    }

    public class PostViewModel
    {
        public string Id { get; set; }

        [Required(ErrorMessage = "Entrer le nom du post")]
        [Display(Name = "Nom")]
        public string NomPost { get; set; }

        [Required(ErrorMessage = "Renseigner le prix svp")]
        [Display(Name = "Prix")]
        public string Prix { get; set; }


        public string Description { get; set; }

        [Display(Name = "Quartier/Ville/Emplacement")]
        [Required(ErrorMessage = "Svp entrez le lieu")]
        public string Lieu { get; set; }

        [Display(Name = "Contrat")] public string TypeContrat { get; set; }
        public List<string> PhotoUrls { get; set; }
    }
}

MCSTOGO/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MCSTOGO.Models;

namespace MCSTOGO.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

MCSTOGO/Controllers/ImmoController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using MCSTOGO.Models;
using MCSTOGO.Services;
using Microsoft.AspNetCore.Components;
using ActionParameterAlias;
using Microsoft.AspNetCore.Mvc;

namespace MCSTOGO.Controllers
{
    public class ImmoController : Controller
    {
        private readonly IPostService _postService;

        public ImmoController(IPostService postService)
        {
            _postService = postService;
        }


        // GET
        public async Task<IActionResult> Index()
        {
            var task = await _postService.ListPost();
            if (task["status"] == "success")
            {
                List<PostViewModel> list = task["data"];
                return View(list);
            }

            if (task["message"] == "Empty List")
            {
                return View(new List<PostViewModel>());
            }

            return View("Error");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> NewPost(PostInputModel post)
        {
            if (ModelState.IsValid)
            {
                var task = await _postService.savePost(post);
                if (task["status"] == "success")
                {
                    return RedirectToAction(nameof(Index));
                }

                return View("Error");
            }

            return View();
        }

        public IActionResult NewPost()
        {
            List<string> contrats = new List<string>() {"Location", "Vente", "Bail"};
            return View();
        }

// [ActionParameterAlias.Alias("postId")]
        public async Task<IActionResult> Info(string postId)
        {
            var post = await _postService.GetPost(postId);
            if (post["status"] == "success")
            {
                PostViewModel p = post["data"];
                return View(p);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

MCSTOGO/Views/Immo/Index.cshtml
@model IEnumerable<PostViewModel>
@{
    Layout = "_GMD";
}
<!-- Navbar and Header -->
<nav class="nav-extended" style="background-color: #0c7cd5!important;">
    <div class="" style="opacity: 1 ; -webkit-filter: grayscale(0%); 
                                                       filter: grayscale(0%);">
        <div class="pattern active" style="background-color: #0c7cd5;"></div>
        @* <img src="~/assets/images/custom/pexels-pixabay-279719.jpg"> *@
    </div>
    <div class="nav-wrapper container">
        <a asp-controller="Home" asp-action="Index" class="brand-logo">MCS - TOGO</a>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger">
            <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
            <li class="active">
                <a asp-controller="Home" asp-action="Index">Accueil</a>
            </li>
        </ul>


        <div class="nav-header center">
            <h1 style="color: white;">Liste de nos articles </h1>

        </div>
    </div>
</nav>

<ul class="sidenav" id="nav-mobile">
    <li class="active"><a asp-action="Index" asp-controller="Home">Accueil</a></li>
    @*<li><a href="index-dark.html"><i class="material-icons">brightness_3</i>Dark Theme</a></li>
    <li><a href="blog.html"><i class="material-icons">edit</i>Blog</a></li>*@
</ul>
<!-- Gallery -->
<div id="portfolio" class="section gray">
    <div class="container">

        <div class="gallery row">
            @if (Model.Any())
            {
                @foreach (var post in Model)
                {
                    <div class="col l4 m6 s12 gallery-item gallery-expand gallery-filter polygon">
                        <div class="gallery-curve-wrapper">

                            <a class="gallery-cover gray" href="@Url.Action("Info", "Immo", new {postId = @post.Id})">

                                <img class="responsive-img" style="height: 250px;background-size:cover; "
                                     src="@post.PhotoUrls.First()" alt="placeholder">
                            </a>
                            <div class="gallery-header">
                                <span>@post.NomPost</span>
                                <p>@post.TypeContrat</p>
                                <p>@post.Prix FCFA</p>
                                <p>@post.Lieu</p>
                                <!-- <span>Aquamarine</span> -->
                            </div>
                            <div class="gallery-body">
                                <div class="title-wrapper">
                                    <h3>@post.NomPost</h3>
                                    <span class="price">@post.Prix FCFA</span>
                                </div>
                                <p class="description">
                                    @post.Description
                                </p>
                                <div class="carousel-wrapper">
                                    <div class="carousel">
                                        @foreach (var PhotoUrl in @post.PhotoUrls)
                                        {
                                            <a class="carousel-item" href="#one!">
                                                <img src="@PhotoUrl" alt="">
                                            </a>
                                        }


                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                }
            }

         
        </div >


    </div>
</div>

@section Scripts
{
    <script type="text/javascript" src="@Url.Content("~/gallery/js/init.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/gallery/js/galleryExpand.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/gallery/js/color-thief.min.js")"></script>
    @* <script type="text/javascript" src="@Url.Content("")"></script> *@
    <script type="text/javascript" src="@Url.Content("~/gallery/js/imagesloaded.pkgd.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/gallery/js/masonry.pkgd.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/gallery/js/materialize.min.js")"></script>
}

MCSTOGO/Views/Immo/Info.cshtml
@model PostViewModel
@{
    Layout = "_MKL";
}

<div class="infobody">
    <div class="page-header header-filter clear-filter white-filter"
         style="background-image: url('@Model.PhotoUrls.First()') ; max-height: 20rem; image-rendering: auto;">

    </div>
    <div class=" main">
        <div class="container">
            <div class="text-center">

                <i class="fa fa-info"></i>
            </div>
            <div class="text-center">

                <p>Informations </p>
            </div>
            <div>
                <div class="text-center">
                    <p class="info-name"> @Model.NomPost </p>
                </div>
            </div>
            <div>
                <div class="row" style="padding: 10px;
                        text-align: left;
                        font-size: 24px;
                        font-weight: 500;
                        color: grey;
                    ">
                    <div class="col-sm-6">
                        <div>
                            <div class="text-center"> Prix </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div>
                            <div class="text-center"> @Model.Prix FCFA</div>
                        </div>

                    </div>
                </div>

            </div>

            <div class="container-fluid">
                <div class="row" style="padding: 10px;
                    text-align: left;
                    font-size: 24px;
                    font-weight: 500;
                    color: grey;">
                    <div class="col-sm-6">
                        <div>
                            <div class="text-center"> Lieu </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div>
                            <div class="text-center"> @Model.Lieu </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p style="max-width: 70%; text-align: justify;">
                    @Model.Description
                </p>
            </div>
            <div class="d-flex justify-content-center align-items-center">
                <a asp-action="Index" class="btn btn-primary btn-round">Retour vers ma page d'accueil</a>
            </div>
            <div style="min-height: 10px;"></div>

        </div>
    </div>

</div>

MCSTOGO/Views/Immo/NewPost.cshtml
@model MCSTOGO.Models.PostInputModel

@{
    ViewBag.Title = "Ajouter un nouvel article";
    Layout = "_MKL";
}

<h2>Ajouter un nouvel article</h2>


<div class="d-flex justify-content-center align-items-center">


    <form enctype="multipart/form-data" asp-action="NewPost">

        <div class="card add-post-card">
            <div class="d-flex justify-content-center align-items-center">
                <i class="fa fa-home" style="    font-size: 45px;
                    color: #9c27b0;"></i>

            </div>
            <div class="d-flex justify-content-center align-items-center">
                <p style="font-size: 24px;
                    font-weight: 700;
                    padding-bottom: 10px;
                    color: grey;">Ajouter un noveau post</p>
            </div>

            <div class="form-group">
                <select class="form-control" asp-for="TypeContrat"
                        asp-items='new List<SelectListItem>() {new SelectListItem("Vente", "Vente"),new SelectListItem("Bail", "Bail"), new SelectListItem("Location", "Location")}'>
                </select>
                <span asp-validation-for="TypeContrat"></span>
            </div>
            <div class="form-group">

                <label asp-for="NomPost"></label>
                <input asp-for="NomPost" class="form-control" id="postNom">
                <span asp-validation-for="NomPost" class="text-danger"></span>
                <!-- <small id="postPrix" class="form-text text-muted">Entrer le prix du post</small> -->
            </div>
            <div class="form-group">
                <label asp-for="Prix"></label>
                <input type="text" class="form-control" asp-for="Prix">
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lieu"></label>
                <input type="text" class="form-control" asp-for="Lieu">
                <span asp-validation-for="Lieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea class="form-control" asp-for="Description"></textarea>
            </div>


            <div class="form-group">
                <label asp-for="Photo1" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Photo1" class="custom-file-input" id="p1Id">
                    <label class="custom-file-label" for="p1Id">Choose file</label>
                </div>
                <span asp-validation-for="Photo1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo2" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="Photo2" class="custom-file-input" id="p2Id">
                    <label class="custom-file-label" for="p2Id">Choose file</label>
                </div>
                <span asp-validation-for="Photo2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary btn-round"/>
                @* <a asp-action="AddPost"></a> *@
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <script type="text/javascript">  
        // Add the following code if you want the name of the file appear on select  
        $("#p1Id").on("change", function () {  
            var fileName = $(this).val().split("\\").pop();  
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);  
        });  
        $("#p2Id").on("change", function () {  
            var fileName = $(this).val().split("\\").pop();  
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);  
        });  
    </script>
}

MCSTOGO/Views/Shared/_GMD.cshtml
@using System.ComponentModel.Design
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Gallery</title>

    <!-- Lato Font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>

    <!-- Stylesheet -->
    <link href="~/gallery/css/gallery-materialize.min.css" rel="stylesheet">

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

@RenderBody()



<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
@* <script src="~/gallery/js/imagesloaded.pkgd.min.js"></script> *@
@* <script src="~/gallery/js/masonry.pkgd.min.js"></script> *@
@* <script src=""></script> *@
@* <script src=""></script> *@
@* <script src=""></script> *@
@* <script src="~/gallery/js/init.js"></script> *@
<script src="~/js/site.js" asp-append-version="true"></script>


@RenderSection("Scripts", required: true)
</body>
</html>

MCSTOGO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - MCSTOGO</title>
    <link rel="stylesheet" href="~/material/css/bootstrap-material-design.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>

@* <header> *@
@*     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
@*         <div class="container"> *@
@*             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MCSTOGO</a> *@
@*             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
@*                     aria-expanded="false" aria-label="Toggle navigation"> *@
@*                 <span class="navbar-toggler-icon"></span> *@
@*             </button> *@
@*             <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse"> *@
@*                 <ul class="navbar-nav flex-grow-1"> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
@*                     </li> *@
@*                     <li class="nav-item"> *@
@*                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
@*                     </li> *@
@*                 </ul> *@
@*             </div> *@
@*         </div> *@
@*     </nav> *@
@* </header> *@
<div class="container">
 
        @RenderBody()

</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - MCSTOGO
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="~/material/js/bootstrap-material-design.min.js"></script>
<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

MCSTOGO/Views/Shared/_MKL.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="~/material-kit/css/site.css" rel="stylesheet" />
    <link href="~/material-kit/css/material-kit.css" rel="stylesheet" />
    @* <link href="~/material-kit/css/fileinput.css" rel="stylesheet" /> *@

    <!-- Font and icons -->
    <link rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
</head>


<body>

@RenderBody()
<script src="~/material-kit/js/core/jquery.min.js" type="text/javascript"></script>
<script src="~/material-kit/js/core/popper.min.js" type="text/javascript"></script>
<script src="~/material-kit/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
<script src="~/material-kit/js/plugins/moment.min.js"></script>
<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
<script src="~/material-kit/js/plugins/bootstrap-datetimepicker.js" type="text/javascript"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="~/material-kit/js/plugins/nouislider.min.js" type="text/javascript"></script>
<!--  Google Maps Plugin  -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
<script src="~/material-kit/js/material-kit.js?v=2.0.4" type="text/javascript"></script>
@* <script src="~/material-kit/js/fileinput.min.js?v=2.0.4" type="text/javascript"></script> *@

@RenderSection("Scripts", required: false)
</body>

</html>

MCSTOGO/Views/Shared/_SinglePageLayout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">

    <!--====== Title ======-->
    <title>Mutuelle Confiance Service</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="assets/images/favicon.png" type="image/png">

    <!--====== Magnific Popup CSS ======-->
    <link rel="stylesheet" href="assets/css/magnific-popup.css">

    <!--====== Slick CSS ======-->
    <link rel="stylesheet" href="assets/css/slick.css">

    <!--====== Line Icons CSS ======-->
    <link rel="stylesheet" href="assets/css/LineIcons.css">

    <!--====== Bootstrap CSS ======-->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css">

    <!--====== Default CSS ======-->
    <link rel="stylesheet" href="assets/css/default.css">

    <!--====== Style CSS ======-->
    <link rel="stylesheet" href="assets/css/style.css">

</head>

<body>

@RenderBody()


<script src="assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="assets/js/vendor/modernizr-3.7.1.min.js"></script>

    <!--====== Bootstrap js ======-->
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>

    <!--====== Slick js ======-->
    <script src="assets/js/slick.min.js"></script>

    <!--====== Magnific Popup js ======-->
    <script src="assets/js/jquery.magnific-popup.min.js"></script>

    <!--====== Ajax Contact js ======-->
    <script src="assets/js/ajax-contact.js"></script>

    <!--====== Isotope js ======-->
    <script src="assets/js/imagesloaded.pkgd.min.js"></script>
    <script src="assets/js/isotope.pkgd.min.js"></script>

    <!--====== Scrolling Nav js ======-->
    <script src="assets/js/jquery.easing.min.js"></script>
    <script src="assets/js/scrolling-nav.js"></script>

    <!--====== Main js ======-->
    <script src="assets/js/main.js"></script>

</body>

</html>